# Generated by Django 3.1.5 on 2021-01-23 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.IntegerField(default=0)),
                ('trans_date', models.DateTimeField(auto_now=True)),
                ('stock_price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(db_column='stock_id', on_delete=django.db.models.deletion.CASCADE, related_name='t_stock', to='stocks.stock')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='t_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
