# Generated by Django 3.1.5 on 2021-01-28 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_stock_stock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_industury',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_sector',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
