# Generated by Django 3.1.5 on 2021-01-28 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20210128_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stock_industury',
            new_name='stock_industry',
        ),
    ]
