# Generated by Django 3.1.5 on 2021-01-28 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20210128_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock_sector',
        ),
    ]
